### ISSUE TITLE
Initial build checks for types before creating them

### ISSUE THREAD

**Issue by kahboom** [module-federation/typescript#10]
Getting the following error on `yarn start`:

```
Error saving the types index [Error: ENOENT: no such file or directory, open 'dist/@mf-typescript/__types_index.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/@mf-typescript/__types_index.json'
}
```

To reproduce:
1. `rm -rf dist`
2. `yarn start`
3. The directory and file are created on that same build, but only _after_ the check, so it fails

If I kill the process and restart it goes away. Of course, I could just check in this file, but I'd rather not have to check in the `dist` dir.

If it's relevant, I'm using dynamic imports.

**Comment by pavandv** [comment]
This issue is been addressed in the #6 PR along with other issues which causes when used with dynamic imports.
