### ISSUE TITLE
Can not determine file extension

### ISSUE THREAD

**Issue by goughjo03** [module-federation/typescript#17]
This error occurs in a module-federation-examples project. specifically this project https://github.com/module-federation/module-federation-examples/tree/master/typescript/app2 at commit 931ea0e5776d1b1f2c68217d9681e5912cda19ec

error message running `yarn start` 

```
<e> [webpack-dev-middleware] Error: Can not determine file extension, please include file extension for the file ./src/Button
<e>     at /module-federation-examples/typescript/app2/node_modules/@module-federation/typescript/src/index.js:118:15
<e>     at Array.forEach (<anonymous>)
<e>     at FederatedTypesPlugin.extractTypes (/module-federation-examples/typescript/app2/node_modules/@module-federation/typescript/src/index.js:109:15)
<e>     at FederatedTypesPlugin.run (/module-federation-examples/typescript/app2/node_modules/@module-federation/typescript/src/index.js:64:12)
<e>     at /module-federation-examples/typescript/app2/node_modules/@module-federation/typescript/src/index.js:58:12
<e>     at Hook.eval [as callAsync] (eval at create (/module-federation-examples/typescript/app2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
<e>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/module-federation-examples/typescript/app2/node_modules/tapable/lib/Hook.js:18:14)
<e>     at /module-federation-examples/typescript/app2/node_modules/webpack/lib/Compiler.js:1192:33
<e>     at finalCallback (/module-federation-examples/typescript/app2/node_modules/webpack/lib/Compilation.js:2787:11)
<e>     at /module-federation-examples/typescript/app2/node_modules/webpack/lib/Compilation.js:3092:11
^C<i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...
```

This error can be avoided by making this change. 

<img width="1178" alt="Screenshot 2022-09-16 at 12 41 54" src="https://user-images.githubusercontent.com/97110316/190631177-9d62444f-ddcb-4ee6-87b1-db6ff78d684c.png">

But then a new error occurs 

```
Error saving the types index [Error: ENOENT: no such file or directory, open 'dist/@mf-typescript/__types_index.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/@mf-typescript/__types_index.json'
}
```

**Comment by pavandv** [comment]
Module Federation examples are not yet updated to the latest version of this package.. You can update the package in the examples and please free to send us a PR in the examples repo with the updated code.

Also we had couple of bug fixes in the recent days which is not yet released. We will release them today or tomorrow.

**Comment by IsmayilAghazada** [comment]
> Module Federation examples are not yet updated to the latest version of this package.. You can update the package in the examples and please free to send us a PR in the examples repo with the updated code.
> 
> Also we had couple of bug fixes in the recent days which is not yet released. We will release them today or tomorrow.

any news related to the release & updates on examples?

**Comment by pavandv** [comment]
I'm currently busy working on module-federation/nextjs-mf#154.

Please feel free to send us a PR with a fix on the examples repo.

And as for the release, I'll ask @ScriptedAlchemy to do a release with latest changes on the main branch.

**Comment by pavandv** [comment]
we have just made a new release `0.2.0`.

Please feel free to create a PR on the examples repo for the other issue.

Closing this issue now. Thanks!

**Comment by goughjo03** [comment]
The problem still exists in that repository with @module-federation/typescript 0.2.1

**Comment by goughjo03** [comment]
This error is coming from the `extractTypes` function:

```
    const normalizedFileNames = [];

    const fileNames = Object.values(this.exposedComponents);

    fileNames.forEach((componentFilePath) => {
      const ext = path.extname(componentFilePath);

      // TODO: Resolve the file ext automatically if not provided in the ModuleFederation Config
      if ([".ts", ".tsx"].includes(ext)) {
        const normalizedPath = path.resolve(process.cwd(), componentFilePath);

        normalizedFileNames.push(normalizedPath);
      } else {
        throw new Error(
          `Can not determine file extension, please include file extension for the file ${componentFilePath}`
        );
      }
    });
```

@pavandv is this check really necessary?

**Comment by pavandv** [comment]
@goughjo03 Yes this check is necessary. 

TS compiler is failing to identify the file extensions if not provided in `moduleFederationPlugin#remotes` configuration and thus failing to generating declarations.

I will enhance this later to automatically resolve the file extension.

**Comment by pavandv** [comment]
That's right!!
