### ISSUE TITLE
remoteComponents is not defined

### ISSUE THREAD

**Issue by guimkogus** [module-federation/typescript#18]
https://github.com/module-federation/typescript/commit/1add36f8d5115c6e82d9e2307769835953e9944a (line 75) introduced an issue removing `this` key word to access `remoteComponents`. See: 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/55510993/191053665-53c60b62-13e9-4f7d-97cb-0fbb425f89b6.png">

Suggestion:
```
importRemoteTypes() {
    const remoteUrls = Object.entries(this.remoteComponents).map(([ remote, entry ]) => {
    const [, url ] = entry.split('@');

    return {
      origin: new URL(url ?? entry).origin,
      remote
    };
  })
...
```

I'd create a PR addressing it but unfortunately I can't :(
<img width="536" alt="image" src="https://user-images.githubusercontent.com/55510993/191054026-53908f23-d31e-4b0d-a86e-396adec3c821.png">

**Comment by pavandv** [comment]
Fixed the issue. Will make a new release.
