### ISSUE TITLE
How does @module-federation/typescript serves/exposes emitted files?

### ISSUE THREAD

**Issue by guimkogus** [module-federation/typescript#21]
My "Shell" app (that doesn't exposes nothing but consumes remote modules) isn't being able to fetch `/@mf-typescript/__types_index.json` neither `*.d.ts` files from remotes, it's getting 404 as if ModuleFederation isn't serving/exposing them.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/55510993/192055110-dcf1aea0-1ace-45bd-815f-29f7fb61817d.png">

I might be missing some config, how does `@module-federation/typescript` serves/exposes emitted files? 🤔 

My project is open source, you can try yourself running https://github.com/PokeFederations/web-app on branch `@module-federation/typescript` (this same branch name exists on each auxiliar modules described in the README file)

**Comment by pavandv** [comment]
I think this is because the path for `handleHelloWorldAlert` in `moduleFederationConfig#exposes` is not resolving correctly. Your webpack config is placed is a webpack folder, but you are referring your component from `src` folder.

https://github.com/PokeFederations/ui-utils/blob/43d27eaedc21d6eeba2b714713b90e6862fa58c5/webpack/webpack.config.cjs#L13

so the correct should be
```js
"./handleHelloWorldAlert": "../src/utils/handleHelloWorldAlert.ts"
```

Notice the **double dots**.

**Comment by guimkogus** [comment]
@pavandv it feels wrong to me too but somehow the correct is using one single dot, otherwise:

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/55510993/192541497-67ca7194-2298-40b5-9227-7815498bce6e.png">

will throw:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/55510993/192541330-811469f8-65be-453b-8c09-37bd1136d7a2.png">

**Comment by guimkogus** [comment]
the issue are related to something else 🤔

**Comment by pavandv** [comment]
Okay, I figured out what the issue is. Will raise a PR soonish.

**Comment by pavandv** [comment]
will make a release today or tomorrow.

**Comment by guimkogus** [comment]
Looking forward for it! Thanks @pavandv
